"""init

Revision ID: 66fd59e0a4ff
Revises: 
Create Date: 2025-11-05 19:25:40.228666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fd59e0a4ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True, comment='设备id'),
    sa.Column('gatewayname', sa.String(), nullable=True, comment='gatewayname'),
    sa.Column('mac', sa.String(), nullable=True, comment='mac'),
    sa.Column('hostname', sa.String(), nullable=True, comment='hostname'),
    sa.Column('dhcp_server', sa.String(), nullable=True, comment='dhcp_server'),
    sa.Column('disk_serial', sa.String(), nullable=True, comment='disk_serial'),
    sa.Column('board_serial', sa.String(), nullable=True, comment='board_serial'),
    sa.Column('cpu_cores', sa.Integer(), nullable=True, comment='cpu_cores'),
    sa.Column('cpu_model', sa.String(), nullable=True, comment='cpu_model'),
    sa.Column('disk_total', sa.String(), nullable=True, comment='disk_total'),
    sa.Column('disk_used', sa.String(), nullable=True, comment='disk_used'),
    sa.Column('disk_avail', sa.String(), nullable=True, comment='disk_avail'),
    sa.Column('disk_usage_percent', sa.String(), nullable=True, comment='disk_usage_percent'),
    sa.Column('mem_total', sa.String(), nullable=True, comment='mem_total'),
    sa.Column('mem_used', sa.String(), nullable=True, comment='mem_used'),
    sa.Column('mem_free', sa.String(), nullable=True, comment='mem_free'),
    sa.Column('mem_usage_percent', sa.String(), nullable=True, comment='mem_usage_percent'),
    sa.Column('ip', sa.String(), nullable=True, comment='ip'),
    sa.Column('status', sa.String(), nullable=True, comment='status'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gatewayname', name='device_uq1')
    )
    op.create_index('device_idx1', 'device', ['gatewayname'], unique=False)
    op.create_index('device_idx2', 'device', ['mac'], unique=False)
    op.create_table('user_behavior',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True, comment='session_id'),
    sa.Column('gatewayname', sa.String(), nullable=True, comment='gatewayname'),
    sa.Column('browser', sa.String(), nullable=True, comment='browser'),
    sa.Column('os', sa.String(), nullable=True, comment='os'),
    sa.Column('device', sa.String(), nullable=True, comment='device'),
    sa.Column('action', sa.String(), nullable=True, comment='action'),
    sa.Column('action_data', sa.String(), nullable=True, comment='action_data'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_behavior_idx1', 'user_behavior', ['gatewayname'], unique=False)
    op.create_index('user_behavior_idx2', 'user_behavior', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_behavior_idx2', table_name='user_behavior')
    op.drop_index('user_behavior_idx1', table_name='user_behavior')
    op.drop_table('user_behavior')
    op.drop_index('device_idx2', table_name='device')
    op.drop_index('device_idx1', table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
