"""change action_data to jsonb

Revision ID: ac1a35d853b7
Revises: 66fd59e0a4ff
Create Date: 2026-03-12 10:39:40.120462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac1a35d853b7'
down_revision: Union[str, Sequence[str], None] = '66fd59e0a4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_behavior', 'action_data',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='action_data::jsonb',
               existing_comment='action_data',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_behavior', 'action_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               postgresql_using='action_data::text',
               existing_comment='action_data',
               existing_nullable=True)
    # ### end Alembic commands ###
